package com.laodev.focus.Utils;

import android.app.ActivityOptions;
import android.content.Context;
import android.content.Intent;
import android.graphics.Bitmap;
import android.location.Address;
import android.location.Geocoder;
import android.util.Log;

import com.laodev.focus.R;
import com.laodev.focus.models.Users;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

public class AppManager {

    public static Users gUserInfo = new Users();

    public static Bitmap gBitmap;
    public static Bitmap gBmpQRCode = null;

    public static String gQuizDate = "";

    static public int friendHomeDispIndex = 0;

    static public Users gFriendUser = new Users();

    static public List<String> gFriendIDList = new ArrayList<>();

    public static String[] gProvinces = {
            "ASUNCIÓN",
            "CONCEPCIÓN",
            "SAN PEDRO",
            "CORDILLERA",
            "GUAIRÁ",
            "CAAGUAZÚ",
            "ITAPÚA",
            "MISIONES",
            "PARAGUARÍ",
            "ALTO PARANÁ",
            "CENTRAL",
            "ÑEEMBUCÚ",
            "AMAMBAY",
            "CANINDEYÚ",
            "PRESIDENTE HAYES",
            "BOQUERÓN",
            "ALTO PARAGUAY",
            "CENTRAL",
            "ÑEEMBUCÚ"};

    public static String[][] gDistricts = {
            {"ASUNCIÓN", "ASUNCIÓN"},
            {"CONCEPCIÓN", "CONCEPCIÓN"},
            {"CONCEPCIÓN", "BELÉN"},
            {"CONCEPCIÓN", "HORQUETA"},
            {"CONCEPCIÓN", "LORETO"},
            {"CONCEPCIÓN", "SAN CARLOS DEL APA"},
            {"CONCEPCIÓN", "SAN LÁZARO"},
            {"CONCEPCIÓN", "YBY YAÚ"},
            {"CONCEPCIÓN", "AZOTE'Y"},
            {"CONCEPCIÓN", "SARGENTO JOSÉ FÉLIX LÓPEZ"},
            {"CONCEPCIÓN", "SAN ALFREDO"},
            {"CONCEPCIÓN", "PASO BARRETO"},
            {"SAN PEDRO", "SAN PEDRO DEL YCUAMANDYYÚ"},
            {"SAN PEDRO", "ANTEQUERA"},
            {"SAN PEDRO", "CHORÉ"},
            {"SAN PEDRO", "GENERAL ELIZARDO AQUINO"},
            {"SAN PEDRO", "ITACURUBÍ DEL ROSARIO"},
            {"SAN PEDRO", "LIMA"},
            {"SAN PEDRO", "NUEVA GERMANIA"},
            {"SAN PEDRO", "SAN ESTANISLAO"},
            {"SAN PEDRO", "SAN PABLO"},
            {"SAN PEDRO", "TACUATÍ"},
            {"SAN PEDRO", "UNIÓN"},
            {"SAN PEDRO", "25 DE DICIEMBRE"},
            {"SAN PEDRO", "VILLA DEL ROSARIO"},
            {"SAN PEDRO", "GENERAL FRANCISCO ISIDORO RESQUÍN"},
            {"SAN PEDRO", "YATAITY DEL NORTE"},
            {"SAN PEDRO", "GUAJAYVI"},
            {"SAN PEDRO", "CAPIIBARY"},
            {"SAN PEDRO", "SANTA ROSA DEL AGUARAY"},
            {"SAN PEDRO", "YRYBUCUA"},
            {"SAN PEDRO", "LIBERACIÓN"},
            {"CORDILLERA", "CAACUPÉ"},
            {"CORDILLERA", "ALTOS"},
            {"CORDILLERA", "ARROYOS Y ESTEROS"},
            {"CORDILLERA", "ATYRÁ"},
            {"CORDILLERA", "CARAGUATAY"},
            {"CORDILLERA", "EMBOSCADA"},
            {"CORDILLERA", "EUSEBIO AYALA"},
            {"CORDILLERA", "ISLA PUCÚ"},
            {"CORDILLERA", "ITACURUBÍ DE LA CORDILLERA"},
            {"CORDILLERA", "JUAN DE MENA"},
            {"CORDILLERA", "LOMA GRANDE"},
            {"CORDILLERA", "MBOCAYATY DEL YHAGUY"},
            {"CORDILLERA", "NUEVA COLOMBIA"},
            {"CORDILLERA", "PIRIBEBUY"},
            {"CORDILLERA", "PRIMERO DE MARZO"},
            {"CORDILLERA", "SAN BERNARDINO"},
            {"CORDILLERA", "SANTA ELENA"},
            {"CORDILLERA", "TOBATÍ"},
            {"CORDILLERA", "VALENZUELA"},
            {"CORDILLERA", "SAN JOSE OBRERO"},
            {"GUAIRÁ", "VILLARRICA"},
            {"GUAIRÁ", "BORJA"},
            {"GUAIRÁ", "CAPITÁN MAURICIO JOSÉ TROCHE"},
            {"GUAIRÁ", "CORONEL MARTÍNEZ"},
            {"GUAIRÁ", "FÉLIX PÉREZ CARDOZO"},
            {"GUAIRÁ", "GRAL. EUGENIO A. GARAY"},
            {"GUAIRÁ", "INDEPENDENCIA"},
            {"GUAIRÁ", "ITAPÉ"},
            {"GUAIRÁ", "ITURBE"},
            {"GUAIRÁ", "JOSÉ FASSARDI"},
            {"GUAIRÁ", "MBOCAYATY"},
            {"GUAIRÁ", "NATALICIO TALAVERA"},
            {"GUAIRÁ", "ÑUMÍ"},
            {"GUAIRÁ", "SAN SALVADOR"},
            {"GUAIRÁ", "YATAITY"},
            {"GUAIRÁ", "DOCTOR BOTTRELL"},
            {"GUAIRÁ", "PASO YOBAI"},
            {"GUAIRÁ", "TEBICUARY"},
            {"CAAGUAZÚ", "CORONEL OVIEDO"},
            {"CAAGUAZÚ", "CAAGUAZÚ"},
            {"CAAGUAZÚ", "CARAYAÓ"},
            {"CAAGUAZÚ", "DR. CECILIO BÁEZ"},
            {"CAAGUAZÚ", "SANTA ROSA DEL MBUTUY"},
            {"CAAGUAZÚ", "DR. JUAN MANUEL FRUTOS"},
            {"CAAGUAZÚ", "REPATRIACIÓN"},
            {"CAAGUAZÚ", "NUEVA LONDRES"},
            {"CAAGUAZÚ", "SAN JOAQUÍN"},
            {"CAAGUAZÚ", "SAN JOSÉ DE LOS ARROYOS"},
            {"CAAGUAZÚ", "YHÚ"},
            {"CAAGUAZÚ", "DR. J. EULOGIO ESTIGARRIBIA"},
            {"CAAGUAZÚ", "R.I. 3 CORRALES"},
            {"CAAGUAZÚ", "RAÚL ARSENIO OVIEDO"},
            {"CAAGUAZÚ", "JOSÉ DOMINGO OCAMPOS"},
            {"CAAGUAZÚ", "MARISCAL FRANCISCO SOLANO LÓPEZ"},
            {"CAAGUAZÚ", "LA PASTORA"},
            {"CAAGUAZÚ", "3 DE FEBRERO"},
            {"CAAGUAZÚ", "SIMÓN BOLIVAR"},
            {"CAAGUAZÚ", "VAQUERÍA"},
            {"CAAGUAZÚ", "TEMBIAPORÁ"},
            {"CAAGUAZÚ", "NUEVA TOLEDO"},
            {"CAAZAPÁ", "CAAZAPÁ"},
            {"CAAZAPÁ", "ABAÍ"},
            {"CAAZAPÁ", "BUENA VISTA"},
            {"CAAZAPÁ", "DR. MOISÉS S. BERTONI"},
            {"CAAZAPÁ", "GRAL. HIGINIO MORINIGO"},
            {"CAAZAPÁ", "MACIEL"},
            {"CAAZAPÁ", "SAN JUAN NEPOMUCENO"},
            {"CAAZAPÁ", "TAVAÍ"},
            {"CAAZAPÁ", "YEGROS"},
            {"CAAZAPÁ", "YUTY"},
            {"CAAZAPÁ", "3 DE MAYO"},
            {"ITAPÚA", "ENCARNACIÓN"},
            {"ITAPÚA", "BELLA VISTA"},
            {"ITAPÚA", "CAMBYRETÁ"},
            {"ITAPÚA", "CAPITÁN MEZA"},
            {"ITAPÚA", "CAPITÁN MIRANDA"},
            {"ITAPÚA", "NUEVA ALBORADA"},
            {"ITAPÚA", "CARMEN DEL PARANÁ"},
            {"ITAPÚA", "CORONEL BOGADO"},
            {"ITAPÚA", "CARLOS ANTONIO LÓPEZ"},
            {"ITAPÚA", "NATALIO"},
            {"ITAPÚA", "FRAM"},
            {"ITAPÚA", "GENERAL ARTIGAS"},
            {"ITAPÚA", "GENERAL DELGADO"},
            {"ITAPÚA", "HOHENAU"},
            {"ITAPÚA", "JESÚS"},
            {"ITAPÚA", "JOSÉ LEANDRO OVIEDO"},
            {"ITAPÚA", "OBLIGADO"},
            {"ITAPÚA", "MAYOR JULIO DIONISIO OTAÑO"},
            {"ITAPÚA", "SAN COSME Y DAMIAN"},
            {"ITAPÚA", "SAN PEDRO DEL PARANÁ"},
            {"ITAPÚA", "SAN RAFAEL DEL PARANÁ"},
            {"ITAPÚA", "TRINIDAD"},
            {"ITAPÚA", "EDELIRA"},
            {"ITAPÚA", "TOMÁS ROMERO PEREIRA"},
            {"ITAPÚA", "ALTO VERÁ"},
            {"ITAPÚA", "LA PAZ"},
            {"ITAPÚA", "YATYTAY"},
            {"ITAPÚA", "SAN JUAN DEL PARANÁ"},
            {"ITAPÚA", "PIRAPÓ"},
            {"ITAPÚA", "ITAPÚA POTY"},
            {"MISIONES", "SAN JUAN BAUTISTA DE LAS MISIONES"},
            {"MISIONES", "AYOLAS"},
            {"MISIONES", "SAN IGNACIO"},
            {"MISIONES", "SAN MIGUEL"},
            {"MISIONES", "SAN PATRIvCIO"},
            {"MISIONES", "SANTA MARÍA"},
            {"MISIONES", "SANTA ROSA"},
            {"MISIONES", "SANTIAGO"},
            {"MISIONES", "VILLA FLORIDA"},
            {"MISIONES", "YABEBYRY"},
            {"PARAGUARÍ", "PARAGUARÍ"},
            {"PARAGUARÍ", "ACAHAY"},
            {"PARAGUARÍ", "CAAPUCÚ"},
            {"PARAGUARÍ", "CABALLERO"},
            {"PARAGUARÍ", "CARAPEGUÁ"},
            {"PARAGUARÍ", "ESCOBAR"},
            {"PARAGUARÍ", "LA COLMENA"},
            {"PARAGUARÍ", "MBUYAPEY"},
            {"PARAGUARÍ", "PIRAYÚ"},
            {"PARAGUARÍ", "QUIINDY"},
            {"PARAGUARÍ", "QUYQUYHÓ"},
            {"PARAGUARÍ", "ROQUE GONZALEZ DE SANTACRUZ"},
            {"PARAGUARÍ", "SAPUCÁI"},
            {"PARAGUARÍ", "TEBICUARY-MÍ"},
            {"PARAGUARÍ", "YAGUARÓN"},
            {"PARAGUARÍ", "YBYCUÍ"},
            {"PARAGUARÍ", "YBYTYMÍ"},
            {"ALTO PARANÁ", "CIUDAD DEL ESTE"},
            {"ALTO PARANÁ", "PRESIDENTE FRANCO"},
            {"ALTO PARANÁ", "DOMINGO MARTÍNEZ DE IRALA"},
            {"ALTO PARANÁ", "DR. JUAN LEÓN MALLORQUÍN"},
            {"ALTO PARANÁ", "HERNANDARIAS"},
            {"ALTO PARANÁ", "ITAKYRY"},
            {"ALTO PARANÁ", "JUAN E. O'LEARY"},
            {"ALTO PARANÁ", "ÑACUNDAY"},
            {"ALTO PARANÁ", "YGUAZÚ"},
            {"ALTO PARANÁ", "LOS CEDRALES"},
            {"ALTO PARANÁ", "MINGA GUAZÚ"},
            {"ALTO PARANÁ", "SAN CRISTOBAL"},
            {"ALTO PARANÁ", "SANTA RITA"},
            {"ALTO PARANÁ", "NARANJAL"},
            {"ALTO PARANÁ", "SANTA ROSA DEL MONDAY"},
            {"ALTO PARANÁ", "MINGA PORÁ"},
            {"ALTO PARANÁ", "MBARACAYÚ"},
            {"ALTO PARANÁ", "SAN ALBERTO"},
            {"ALTO PARANÁ", "IRUÑA"},
            {"ALTO PARANÁ", "SANTA FE DEL PARANÁ"},
            {"ALTO PARANÁ", "TAVAPY"},
            {"ALTO PARANÁ", "DR. RAÚL PEÑA"},
            {"CENTRAL", "AREGUÁ"},
            {"CENTRAL", "CAPIATÁ"},
            {"CENTRAL", "FERNANDO DE LA MORA"},
            {"CENTRAL", "GUARAMBARÉ"},
            {"CENTRAL", "ITÁ"},
            {"CENTRAL", "ITAUGUÁ"},
            {"CENTRAL", "LAMBARÉ"},
            {"CENTRAL", "LIMPIO"},
            {"CENTRAL", "LUQUE"},
            {"CENTRAL", "MARIANO ROQUE ALONSO"},
            {"CENTRAL", "NUEVA ITALIA"},
            {"CENTRAL", "ÑEMBY"},
            {"CENTRAL", "SAN ANTONIO"},
            {"CENTRAL", "SAN LORENZO"},
            {"CENTRAL", "VILLA ELISA"},
            {"CENTRAL", "VILLETA"},
            {"CENTRAL", "YPACARAÍ"},
            {"CENTRAL", "YPANÉ"},
            {"CENTRAL", "J. AUGUSTO SALDIVAR"},
            {"ÑEEMBUCÚ", "PILAR"},
            {"ÑEEMBUCÚ", "ALBERDI"},
            {"ÑEEMBUCÚ", "CERRITO"},
            {"ÑEEMBUCÚ", "DESMOCHADOS"},
            {"ÑEEMBUCÚ", "GRAL. JOSÉ EDUVIGIS DÍAZ"},
            {"ÑEEMBUCÚ", "GUAZÚ-CUÁ"},
            {"ÑEEMBUCÚ", "HUMAITÁ"},
            {"ÑEEMBUCÚ", "ISLA UMBÚ"},
            {"ÑEEMBUCÚ", "LAURELES"},
            {"ÑEEMBUCÚ", "MAYOR JOSÉ DEJESÚS MARTÍNEZ"},
            {"ÑEEMBUCÚ", "PASO DE PATRIA"},
            {"ÑEEMBUCÚ", "SAN JUAN BAUTISTA DE ÑEEMBUCÚ"},
            {"ÑEEMBUCÚ", "TACUARAS"},
            {"ÑEEMBUCÚ", "VILLA FRANCA"},
            {"ÑEEMBUCÚ", "VILLA OLIVA"},
            {"ÑEEMBUCÚ", "VILLALBÍN"},
            {"AMAMBAY", "PEDRO JUAN CABALLERO"},
            {"AMAMBAY", "BELLA VISTA"},
            {"AMAMBAY", "CAPITÁN BADO"},
            {"AMAMBAY", "ZANJA PYTÃ"},
            {"AMAMBAY", "KARAPAÍ"},
            {"CANINDEYÚ", "SALTO DEL GUAIRÁ"},
            {"CANINDEYÚ", "CORPUS CHRISTI"},
            {"CANINDEYÚ", "VILLA CURUGUATY"},
            {"CANINDEYÚ", "VILLA YGATIMÍ"},
            {"CANINDEYÚ", "ITANARÁ"},
            {"CANINDEYÚ", "YPEJHÚ"},
            {"CANINDEYÚ", "FRANCISCO CABALLERO ALVAREZ"},
            {"CANINDEYÚ", "KATUETÉ"},
            {"CANINDEYÚ", "LA PALOMA DEL ESPÍRITU SANTO"},
            {"CANINDEYÚ", "NUEVA ESPERANZA"},
            {"CANINDEYÚ", "YASY CAÑY"},
            {"CANINDEYÚ", "YBYRAROBANÁ"},
            {"CANINDEYÚ", "YBY PYTÁ"},
            {"PRESIDENTE HAYES", "BENJAMÍN ACEVAL"},
            {"PRESIDENTE HAYES", "PUERTO PINASCO"},
            {"PRESIDENTE HAYES", "VILLA HAYES"},
            {"PRESIDENTE HAYES", "NANAWA"},
            {"PRESIDENTE HAYES", "JOSÉ FALCÓN"},
            {"PRESIDENTE HAYES", "TTE. 1° MANUEL IRALA FERNÁNDEZ"},
            {"PRESIDENTE HAYES", "TENIENTE ESTEBAN MARTÍNEZ"},
            {"PRESIDENTE HAYES", "GENERAL JOSÉ MARÍA BRUGUEZ"},
            {"BOQUERÓN", "MARISCAL JOSÉ FÉLIX ESTIGARRIBIA"},
            {"BOQUERÓN", "FILADELFIA"},
            {"BOQUERÓN", "LOMA PLATA"},
            {"ALTO PARAGUAY", "FUERTE OLIMPO"},
            {"ALTO PARAGUAY", "PUERTO CASADO"},
            {"ALTO PARAGUAY", "BAHÍA NEGRA"},
            {"ALTO PARAGUAY", "CARMELO PERALTA"}
    };

    public static void showOtherActivity (Context context, Class<?> cls, int direction) {
        Intent myIntent = new Intent(context, cls);
        ActivityOptions options;
        switch (direction) {
            case 0:
                options = ActivityOptions.makeCustomAnimation(context, R.anim.slide_in_right, R.anim.slide_out_left);
                context.startActivity(myIntent, options.toBundle());
                break;
            case 1:
                options = ActivityOptions.makeCustomAnimation(context, R.anim.slide_in_left, R.anim.slide_out_right);
                context.startActivity(myIntent, options.toBundle());
                break;
            default:
                context.startActivity(myIntent);
                break;
        }
    }

}
